### ISSUE TITLE
[poddisruptionbudgettrait] When the trait uses workloadtype as deployment, there will be crash

### ISSUE THREAD

**Issue by linjiemiao** [oam-dev/catalog#62]
Look at the following example:

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: example-component
    spec:
      selector:
        matchLabels:
          app: example-component
      template:
        metadata:
          labels:
            app: example-component
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
              name: pa
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-component
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: PodDisruptionBudgetTrait
            metadata:
              name: example-pdb-trait
            spec:
              minAvailable: 1
```

After deployment, the controller will have the following errors:

```
2020-11-03T08:57:15.622Z	INFO	controllers.PodDisruptionBudgetTrait	Cannot locate any resources	{"total resources": 0}
E1103 08:57:15.649445       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 307 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14db100, 0x23a9050)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14db100, 0x23a9050)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/api/policy/v1beta1.(*PodDisruptionBudget).GetObjectKind(0x0, 0xc0003d0100, 0x18f95c0)
	<autogenerated>:1 +0x5
sigs.k8s.io/controller-runtime/pkg/client.(*client).Patch(0xc0000e63f0, 0x18bf120, 0xc0000560b0, 0x18922e0, 0x0, 0x18961e0, 0x23e4df8, 0xc0005d5ce0, 0x2, 0x2, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/client/client.go:151 +0x57
github.com/oam-dev/catalog/traits/poddisruptionbudgettrait/controllers.(*PodDisruptionBudgetTraitReconciler).Reconcile(0xc0003d0100, 0xc000489c2c, 0x4, 0xc000380900, 0x11, 0xc0003ae518, 0x1895480, 0xc0003ae510, 0xc0003adcb0)
	/workspace/controllers/poddisruptionbudgettrait_controller.go:110 +0xe96
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000504b40, 0x1531360, 0xc0003b1940, 0x43e600)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:233 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000504b40, 0xc00048e600)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:209 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000504b40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005183e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:155 +0x5e
```
* solution

We revised the definition of workload (deployment)：

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  creationTimestamp: "2020-11-02T05:22:33Z"
  generation: 3
  name: deployments.apps
  resourceVersion: "164262607"
  selfLink: /apis/core.oam.dev/v1alpha2/workloaddefinitions/deployments.apps
  uid: e552e772-8810-4d01-8414-094ba1f43668
spec:
  childResourceKinds:
  - apiVersion: apps/v1
    kind: ReplicaSet
  definitionRef:
    name: deployments.apps
```
